/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UAVModel_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* UAVModel_expl_ode_fun:(i0[17],i1[4],i2[])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=1.3966480446927374e+00;
  a1=2.;
  a2=arg[0]? arg[0][10] : 0;
  a3=arg[0]? arg[0][12] : 0;
  a4=(a2*a3);
  a5=arg[0]? arg[0][9] : 0;
  a6=arg[0]? arg[0][11] : 0;
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a1*a4);
  a4=(a0*a4);
  a7=arg[0]? arg[0][13] : 0;
  a8=arg[0]? arg[0][14] : 0;
  a9=(a7+a8);
  a10=arg[0]? arg[0][15] : 0;
  a9=(a9+a10);
  a11=arg[0]? arg[0][16] : 0;
  a9=(a9+a11);
  a4=(a4*a9);
  if (res[0]!=0) res[0][3]=a4;
  a4=(a6*a3);
  a12=(a5*a2);
  a4=(a4-a12);
  a4=(a1*a4);
  a4=(a0*a4);
  a4=(a4*a9);
  if (res[0]!=0) res[0][4]=a4;
  a4=-9.8100000000000005e+00;
  a12=1.;
  a13=casadi_sq(a2);
  a14=casadi_sq(a6);
  a13=(a13+a14);
  a1=(a1*a13);
  a12=(a12-a1);
  a0=(a0*a12);
  a0=(a0*a9);
  a4=(a4+a0);
  if (res[0]!=0) res[0][5]=a4;
  a4=1.4285714285714286e+02;
  a0=1.7000000000000001e-01;
  a9=(a0*a8);
  a12=-1.7000000000000001e-01;
  a1=(a12*a11);
  a9=(a9+a1);
  a1=arg[0]? arg[0][7] : 0;
  a13=1.2000000000000000e-02;
  a14=arg[0]? arg[0][8] : 0;
  a13=(a13*a14);
  a15=(a1*a13);
  a16=7.0000000000000001e-03;
  a17=(a16*a1);
  a18=(a14*a17);
  a15=(a15-a18);
  a9=(a9-a15);
  a9=(a4*a9);
  if (res[0]!=0) res[0][6]=a9;
  a12=(a12*a7);
  a0=(a0*a10);
  a12=(a12+a0);
  a0=arg[0]? arg[0][6] : 0;
  a16=(a16*a0);
  a9=(a14*a16);
  a13=(a0*a13);
  a9=(a9-a13);
  a12=(a12-a9);
  a4=(a4*a12);
  if (res[0]!=0) res[0][7]=a4;
  a4=8.3333333333333329e+01;
  a12=1.6000000000000000e-02;
  a9=(a12*a7);
  a13=-1.6000000000000000e-02;
  a15=(a13*a8);
  a9=(a9+a15);
  a12=(a12*a10);
  a9=(a9+a12);
  a13=(a13*a11);
  a9=(a9+a13);
  a17=(a0*a17);
  a16=(a1*a16);
  a17=(a17-a16);
  a9=(a9-a17);
  a4=(a4*a9);
  if (res[0]!=0) res[0][8]=a4;
  a4=5.0000000000000000e-01;
  a9=(a2*a0);
  a17=(a6*a1);
  a9=(a9+a17);
  a17=(a3*a14);
  a9=(a9+a17);
  a9=(a4*a9);
  a9=(-a9);
  if (res[0]!=0) res[0][9]=a9;
  a9=(a5*a0);
  a17=(a6*a14);
  a9=(a9+a17);
  a17=(a3*a1);
  a9=(a9-a17);
  a9=(a4*a9);
  if (res[0]!=0) res[0][10]=a9;
  a9=(a5*a1);
  a17=(a2*a14);
  a9=(a9-a17);
  a3=(a3*a0);
  a9=(a9+a3);
  a9=(a4*a9);
  if (res[0]!=0) res[0][11]=a9;
  a5=(a5*a14);
  a2=(a2*a1);
  a5=(a5+a2);
  a6=(a6*a0);
  a5=(a5-a6);
  a4=(a4*a5);
  if (res[0]!=0) res[0][12]=a4;
  a4=40.;
  a5=arg[1]? arg[1][0] : 0;
  a5=(a5-a7);
  a5=(a4*a5);
  if (res[0]!=0) res[0][13]=a5;
  a5=arg[1]? arg[1][1] : 0;
  a5=(a5-a8);
  a5=(a4*a5);
  if (res[0]!=0) res[0][14]=a5;
  a5=arg[1]? arg[1][2] : 0;
  a5=(a5-a10);
  a5=(a4*a5);
  if (res[0]!=0) res[0][15]=a5;
  a5=arg[1]? arg[1][3] : 0;
  a5=(a5-a11);
  a4=(a4*a5);
  if (res[0]!=0) res[0][16]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UAVModel_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int UAVModel_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real UAVModel_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAVModel_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAVModel_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAVModel_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAVModel_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
